// GENERATED by scripts/export-golden-fixtures.mjs from src/utils/changelog.ts. Do not edit.

class ChangelogEntry {
  const ChangelogEntry(this.version, this.date, this.changes);
  final String version;
  final String date;
  final List<String> changes;
}

const List<ChangelogEntry> changelogEntries = [
  ChangelogEntry('3.46.1', '2026-10-07', [
    'Behind the scenes: fixed the Flutter Android build (core library desugaring for local notifications). No change to the web app.',
  ]),
  ChangelogEntry('3.46.0', '2026-10-07', [
    'Behind the scenes: Flutter migration Phases 10-12 (notifications, settings, push and reminders, feedback, version gate, accessibility fixes, release hardening, cutover and rollout plans). No change to the web app.',
  ]),
  ChangelogEntry('3.45.0', '2026-10-06', [
    'Behind the scenes: Flutter migration Phase 9 (maps, live location, receipts OCR, weather, Trip Wrapped, squad badges, traveler passport, ICS calendar export, Next Up capsule & gate scanner). No change to the web app.',
  ]),
  ChangelogEntry('3.44.3', '2026-10-06', [
    'Behind the scenes: groundwork for Flutter migration Phase 8 (members, notes, chat, boarding passes). No change to the web app.',
  ]),
  ChangelogEntry('3.44.2', '2026-10-06', [
    'Behind the scenes: groundwork for Flutter migration Phase 7 slices E-G (ledger loop, UPI, share card, close-out). No change to the web app.',
  ]),
  ChangelogEntry('3.44.1', '2026-10-06', [
    'Behind the scenes: groundwork for the upcoming native mobile app (expense form and balances screens). No change to the web app.',
  ]),
  ChangelogEntry('3.43.11', '2026-10-05', [
    'The Amount box in Add Expense now sits immediately below its label for faster entry, with currency suggestions underneath.',
    'Split presets, quick amount additions, stepper dots, and currency toggles now have enlarged 44px tap targets for easier mobile tapping.',
    'Restored draft notices are calmer, and the bottom save bar has subtle elevation above scrolling form content.',
  ]),
  ChangelogEntry('3.43.10', '2026-10-02', [
    'The Members list and live packing updates from the previous release now reach the site. That build had stopped on a type error.',
  ]),
  ChangelogEntry('3.43.9', '2026-10-02', [
    'Packing, notes, and passes now show up for everyone immediately, the same way a Talk message does.',
    'The Members tab is a simple list: one role per person, the balance on the right, and groups in the same quiet style.',
  ]),
  ChangelogEntry('3.43.8', '2026-10-02', [
    'Packing lists, notes, and passes now stay in sync for everyone on the trip. An add, edit, or delete by one member shows up for the others without a reload.',
    'Expenses, members, and the summary refresh the same way while the trip is open.',
  ]),
  ChangelogEntry('3.43.7', '2026-10-02', [
    'Small labels and captions across the app are now at least 11px, so they are easier to read.',
    'Small icon buttons are easier to tap, and screen readers now announce more pop-ups as dialogs.',
    'Marking a payment as settled now shows a clear card with who pays whom and how much.',
    'New: the Summary pass shows a one-time hint that it flips to your own balance.',
  ]),
  ChangelogEntry('3.43.6', '2026-10-02', [
    'Summary now labels your own balance and the group total separately, so the two numbers are no longer confused.',
    'If you are in a couple or group, the flipped pass shows how your balance splits inside and outside the group.',
    'The bottom bar is more solid, so cards no longer show through it, and the top chips are easier to tap.',
    'The "You’re owed" chip says "see who" instead of promising a reminder it did not send.',
  ]),
];
