// GENERATED by scripts/export-golden-fixtures.mjs from src/utils/changelog.ts. Do not edit.

class ChangelogEntry {
  const ChangelogEntry(this.version, this.date, this.changes);
  final String version;
  final String date;
  final List<String> changes;
}

const List<ChangelogEntry> changelogEntries = [
  ChangelogEntry('3.48.1', '2026-10-08', [
    'Behind the scenes: fixed the Flutter CI fixtures-drift check. No change to the web app.',
  ]),
  ChangelogEntry('3.48.0', '2026-10-08', [
    'Behind the scenes: Flutter Horizon redesign across all screens, desktop layouts, Balances and Spend Insights behind new flags. No change to the web app.',
  ]),
  ChangelogEntry('3.47.0', '2026-10-08', [
    'Behind the scenes: Flutter migration Horizon redesign, Web platform compilation with Wasm SQLite, and Google-only + Superadmin authentication gate. No change to the web app.',
  ]),
  ChangelogEntry('3.46.1', '2026-10-07', [
    'Behind the scenes: fixed the Flutter Android build (core library desugaring for local notifications). No change to the web app.',
  ]),
  ChangelogEntry('3.46.0', '2026-10-07', [
    'Behind the scenes: Flutter migration Phases 10-12 (notifications, settings, push and reminders, feedback, version gate, accessibility fixes, release hardening, cutover and rollout plans). No change to the web app.',
  ]),
  ChangelogEntry('3.45.0', '2026-10-06', [
    'Behind the scenes: Flutter migration Phase 9 (maps, live location, receipts OCR, weather, Trip Wrapped, squad badges, traveler passport, ICS calendar export, Next Up capsule & gate scanner). No change to the web app.',
  ]),
  ChangelogEntry('3.44.3', '2026-10-06', [
    'Behind the scenes: groundwork for Flutter migration Phase 8 (members, notes, chat, boarding passes). No change to the web app.',
  ]),
  ChangelogEntry('3.44.2', '2026-10-06', [
    'Behind the scenes: groundwork for Flutter migration Phase 7 slices E-G (ledger loop, UPI, share card, close-out). No change to the web app.',
  ]),
  ChangelogEntry('3.44.1', '2026-10-06', [
    'Behind the scenes: groundwork for the upcoming native mobile app (expense form and balances screens). No change to the web app.',
  ]),
  ChangelogEntry('3.43.11', '2026-10-05', [
    'The Amount box in Add Expense now sits immediately below its label for faster entry, with currency suggestions underneath.',
    'Split presets, quick amount additions, stepper dots, and currency toggles now have enlarged 44px tap targets for easier mobile tapping.',
    'Restored draft notices are calmer, and the bottom save bar has subtle elevation above scrolling form content.',
  ]),
  ChangelogEntry('3.43.10', '2026-10-02', [
    'The Members list and live packing updates from the previous release now reach the site. That build had stopped on a type error.',
  ]),
  ChangelogEntry('3.43.9', '2026-10-02', [
    'Packing, notes, and passes now show up for everyone immediately, the same way a Talk message does.',
    'The Members tab is a simple list: one role per person, the balance on the right, and groups in the same quiet style.',
  ]),
];
