// GENERATED by scripts/export-golden-fixtures.mjs from src/utils/changelog.ts. Do not edit.

class ChangelogEntry {
  const ChangelogEntry(this.version, this.date, this.changes);
  final String version;
  final String date;
  final List<String> changes;
}

const List<ChangelogEntry> changelogEntries = [
  ChangelogEntry('3.56.0', '2026-10-10', [
    'Behind the scenes: the Flutter app has a boarding-gate sign-in screen, a redesigned "Departures" card stack with an airport runway slider for New Trip and Join, and a Create Trip form that starts with the destination and suggests the trip name. Superadmin sessions are never restored automatically. No change to the web app.',
  ]),
  ChangelogEntry('3.55.0', '2026-10-09', [
    'Behind the scenes: the Flutter app has a native Superadmin portal (overview, bug ledger, users, trips, flags, analytics, audit, controls and tools) and a card-stack view for the Trips home screen with destination photos. No change to the web app.',
  ]),
  ChangelogEntry('3.54.0', '2026-10-09', [
    'Behind the scenes: the Flutter app has a boarding-pass look for Summary, Expenses and Passes, and the Fewest / Per person switch now updates right away instead of snapping back. No change to the web app.',
  ]),
  ChangelogEntry('3.53.0', '2026-10-09', [
    'Trip Members: Adding a person now requires a mandatory Gmail ID (@gmail.com) with smart auto-completion, real-time Google account preview, and automatic member claiming across Flutter and Web.',
  ]),
  ChangelogEntry('3.52.0', '2026-10-09', [
    'Behind the scenes: Flutter app features Summary-first tabs, boarding pass summary hero, live Notes checklist with live editing, and realtime trip chat sync.',
  ]),
  ChangelogEntry('3.51.0', '2026-10-09', [
    'Behind the scenes: the Flutter app has a new Bento look with pastel tiles, new fonts and a floating bottom bar, in light, dark and black themes. No change to the web app.',
  ]),
  ChangelogEntry('3.50.1', '2026-10-09', [
    'Behind the scenes: Flutter Superadmin login now opens a Superadmin screen whose Ops Deck button signs you straight into the web portal, and web links open correctly on Android. No change to the web app.',
  ]),
  ChangelogEntry('3.50.0', '2026-10-09', [
    'Behind the scenes: Flutter app now uses the web app colours (teal and orange), passes show as cards, and Superadmin login opens a Superadmin screen. No change to the web app.',
  ]),
  ChangelogEntry('3.49.0', '2026-10-09', [
    'Behind the scenes: Flutter Notes tab no longer overflows on trips with many passes, and passes can be sorted by time, flight leg, or traveler name. No change to the web app.',
  ]),
  ChangelogEntry('3.48.2', '2026-10-08', [
    'Behind the scenes: Flutter app now shows trips right after sign-in, suggests destinations while typing, and the Horizon navigation and Spend Insights are on by default. No change to the web app.',
  ]),
  ChangelogEntry('3.48.1', '2026-10-08', [
    'Behind the scenes: fixed the Flutter CI fixtures-drift check. No change to the web app.',
  ]),
  ChangelogEntry('3.48.0', '2026-10-08', [
    'Behind the scenes: Flutter Horizon redesign across all screens, desktop layouts, Balances and Spend Insights behind new flags. No change to the web app.',
  ]),
];
