// GENERATED by scripts/export-golden-fixtures.mjs from DEFAULT_CATEGORIES in src/store/tripStore.ts. Do not edit.
import '../models/category.dart';

const List<Category> defaultCategories = [
  Category(id: 'cat-food', name: 'Food & Dining', icon: '🍔', isCustom: false),
  Category(id: 'cat-stay', name: 'Stay & Hotel', icon: '🏨', isCustom: false),
  Category(id: 'cat-travel', name: 'Travel & Transport', icon: '✈️', isCustom: false),
  Category(id: 'cat-activities', name: 'Activities & Sightseeing', icon: '🎟️', isCustom: false),
  Category(id: 'cat-shopping', name: 'Shopping', icon: '🛍️', isCustom: false),
  Category(id: 'cat-misc', name: 'Misc & Others', icon: '📦', isCustom: false),
];
