/**
 * Comprehensive Dataset of 200+ Trip Items & Global/Regional Brands
 * Used for Title-to-Category Auto-Tagging.
 *
 * Tier 1: Top 50 Hardcoded Core (Brands + Items)
 * Tier 2: Extended 150+ Editable Keyword List
 */

export interface KeywordDataset {
  brands: string[];
  items: string[];
}

// ---------------------------------------------------------------------------
// Tier 1: Top 50 Hardcoded Core (Guaranteed priority matching)
// ---------------------------------------------------------------------------

export const TOP_50_BRANDS: Record<string, string[]> = {
  'cat-food': [
    'swiggy',
    'zomato',
    'starbucks',
    'mcdonald',
    'mcdonalds',
    'kfc',
    'burger king',
    'dominos',
    'pizza hut',
    'subway',
    'blinkit',
    'zepto',
    'instamart',
    'dunkin',
    'chai point',
    'blue tokai',
  ],
  'cat-travel': [
    'uber',
    'ola',
    'rapido',
    'indigo',
    'air india',
    'spicejet',
    'makemytrip',
    'irctc',
    'redbus',
    'shell',
    'hpcl',
    'bpcl',
    'indianoil',
    'fastag',
    'grab',
    'lyft',
  ],
  'cat-stay': [
    'airbnb',
    'booking.com',
    'agoda',
    'oyo',
    'marriott',
    'hilton',
    'hyatt',
    'taj',
    'zostel',
    'hostelworld',
  ],
  'cat-activities': [
    'bookmyshow',
    'klook',
    'getyourguide',
    'disney',
    'universal studios',
    'imax',
    'pvr',
  ],
  'cat-shopping': [
    'zara',
    'h&m',
    'uniqlo',
    'decathlon',
    'amazon',
    'flipkart',
    'duty free',
  ],
  'cat-misc': [
    'apollo pharmacy',
    'medplus',
    'airtel',
    'jio',
    'google pay',
    'forex',
  ],
};

export const TOP_50_ITEMS: Record<string, string[]> = {
  'cat-food': [
    'milk',
    'maggi',
    'maggie',
    'bread',
    'eggs',
    'butter',
    'coffee',
    'chai',
    'tea',
    'beer',
    'wine',
    'whiskey',
    'pizza',
    'burger',
    'biryani',
    'breakfast',
    'lunch',
    'dinner',
    'snacks',
    'chips',
    'water',
    'groceries',
    'ice cream',
  ],
  'cat-travel': [
    'petrol',
    'diesel',
    'fuel',
    'toll',
    'parking',
    'flight',
    'train',
    'bus',
    'metro',
    'cab',
    'taxi',
    'auto',
    'rickshaw',
    'scooter rental',
    'car rental',
    'driver tip',
  ],
  'cat-stay': [
    'hotel',
    'hostel',
    'resort',
    'homestay',
    'villa',
    'room service',
    'late checkout',
    'city tax',
    'lodge',
    'dorm',
  ],
  'cat-activities': [
    'museum',
    'tickets',
    'safari',
    'scuba',
    'diving',
    'trek',
    'tour guide',
    'cinema',
    'movie',
    'theme park',
    'monument',
  ],
  'cat-shopping': [
    'shopping',
    'souvenir',
    'gifts',
    'clothes',
    'shoes',
    'jacket',
    'sunglasses',
    'sunscreen',
  ],
  'cat-misc': [
    'medicine',
    'pharmacy',
    'bandaid',
    'sim card',
    'esim',
    'laundry',
    'tips',
    'atm fee',
    'currency exchange',
  ],
};

// ---------------------------------------------------------------------------
// Tier 2: Extended 150+ Keywords (Combined with Top 50 to form complete 200+ list)
// ---------------------------------------------------------------------------

export const DEFAULT_EXTENDED_KEYWORDS: Record<string, KeywordDataset> = {
  'cat-food': {
    brands: [
      ...TOP_50_BRANDS['cat-food'],
      'bigbasket',
      'natures basket',
      '7-eleven',
      'tim hortons',
      'costa coffee',
      'chipotle',
      'taco bell',
      'wendys',
      'baskin robbins',
      'haldiram',
      'third wave coffee',
      'hard rock cafe',
      'nandos',
      'pret a manger',
      'chaayos',
      'krispy kreme',
      'bikanervala',
      'subway eats',
      'popeyes',
      'carls jr',
      'star market',
      'whole foods',
    ],
    items: [
      ...TOP_50_ITEMS['cat-food'],
      'mineral water',
      'cold drink',
      'coke',
      'pepsi',
      'cocktail',
      'mocktail',
      'alcohol',
      'thali',
      'noodles',
      'pasta',
      'dosa',
      'idli',
      'paratha',
      'sandwich',
      'pastry',
      'cake',
      'cookies',
      'biscuits',
      'curd',
      'yogurt',
      'paneer',
      'cheese',
      'chicken',
      'mutton',
      'fish',
      'seafood',
      'fruits',
      'apple',
      'banana',
      'vegetables',
      'salad',
      'dessert',
      'sweet',
      'mithai',
      'buffet',
      'dining',
      'restaurant',
      'cafe',
      'dhaba',
      'street food',
      'barbeque',
      'bbq',
      'steak',
      'sushi',
      'ramen',
      'tacos',
      'croissant',
    ],
  },
  'cat-travel': {
    brands: [
      ...TOP_50_BRANDS['cat-travel'],
      'vistara',
      'emirates',
      'qatar airways',
      'cleartrip',
      'flixbus',
      'avis',
      'hertz',
      'zoomcar',
      'bolt',
      'totalenergies',
      'eurail',
      'shinkansen',
      'singapore airlines',
      'klm',
      'lufthansa',
      'etihad',
      'ryanair',
      'easyjet',
      'airasia',
      'flydubai',
      'enterprise rent-a-car',
      'sixt',
      'europcar',
    ],
    items: [
      ...TOP_50_ITEMS['cat-travel'],
      'gas',
      'cng',
      'ev charging',
      'fastag recharge',
      'toll gate',
      'valet parking',
      'airport taxi',
      'airport transfer',
      'boarding pass',
      'baggage fee',
      'excess baggage',
      'ferry',
      'boat',
      'speed boat',
      'yacht',
      'cable car',
      'gondola',
      'tram',
      'tuktuk',
      'commute',
      'intercity bus',
      'sleeper bus',
      'speed train',
      'railway ticket',
      'highway toll',
      'expressway',
    ],
  },
  'cat-stay': {
    brands: [
      ...TOP_50_BRANDS['cat-stay'],
      'radisson',
      'vrbo',
      'trivago',
      'treebo',
      'fabhotels',
      'accor',
      'ibis',
      'novotel',
      'sheraton',
      'four seasons',
      'leela',
      'lemon tree',
      'ginger hotel',
      'club med',
      'westin',
      'mercure',
    ],
    items: [
      ...TOP_50_ITEMS['cat-stay'],
      'cottage',
      'tent',
      'camp',
      'glamping',
      'caravan',
      'bed and breakfast',
      'b&b',
      'guest house',
      'motel',
      'chalet',
      'cabin',
      'early checkin',
      'security deposit',
      'extra bed',
      'resort fee',
      'cleaning fee',
      'accommodation',
      'staycation',
    ],
  },
  'cat-activities': {
    brands: [
      ...TOP_50_BRANDS['cat-activities'],
      'tripadvisor',
      'viator',
      'inox',
      'cinepolis',
      'wonderla',
      'imagica',
      'six flags',
      'madame tussauds',
    ],
    items: [
      ...TOP_50_ITEMS['cat-activities'],
      'snorkeling',
      'bungee',
      'bungee jumping',
      'paragliding',
      'parasailing',
      'kayaking',
      'rafting',
      'white water rafting',
      'zipline',
      'snicker',
      'surfing',
      'skiing',
      'snowboarding',
      'monument entry',
      'palace',
      'fort',
      'temple entry',
      'church',
      'aquarium',
      'zoo',
      'botanical garden',
      'national park',
      'audio guide',
      'concert ticket',
      'live music',
      'nightclub entry',
      'amusement park',
      'water park',
      'show ticket',
      'ferris wheel',
      'observation deck',
    ],
  },
  'cat-shopping': {
    brands: [
      ...TOP_50_BRANDS['cat-shopping'],
      'nike',
      'adidas',
      'puma',
      'sephora',
      'apple store',
      'miniso',
      'target',
      'walmart',
      'ikea',
      'boots',
      'marks and spencer',
      'muji',
      'lush',
      'bath & body works',
    ],
    items: [
      ...TOP_50_ITEMS['cat-shopping'],
      'tshirt',
      'dress',
      'pants',
      'swimwear',
      'swimsuit',
      'slippers',
      'flipflops',
      'hat',
      'cap',
      'handicrafts',
      'local sweets',
      'fridge magnet',
      'postcard',
      'perfume',
      'cosmetics',
      'makeup',
      'lotion',
      'bag',
      'backpack',
      'luggage',
      'suitcase',
      'outlet store',
      'mall',
      'flea market',
      'bazaar',
    ],
  },
  'cat-misc': {
    brands: [
      ...TOP_50_BRANDS['cat-misc'],
      'cvs',
      'walgreens',
      'vodafone',
      'vi',
      'wise',
      'western union',
      'revolut',
      't-mobile',
    ],
    items: [
      ...TOP_50_ITEMS['cat-misc'],
      'first aid',
      'painkiller',
      'paracetamol',
      'aspirin',
      'ointment',
      'mosquito repellent',
      'sanitizer',
      'mask',
      'data recharge',
      'roaming pack',
      'mobile topup',
      'wifi pass',
      'lock',
      'luggage lock',
      'travel adapter',
      'power bank',
      'charging cable',
      'umbrella',
      'raincoat',
      'photocopy',
      'printout',
      'visa fee',
      'passport fee',
      'service charge',
      'lockers',
    ],
  },
};
