import type { FeatureFlagKey, FeatureFlagMeta, ReleasePhaseDef, ReleasePhaseId } from '../types/admin';

export const RELEASE_PHASES: ReleasePhaseDef[] = [
  {
    id: 'phase1',
    phaseNumber: 1,
    code: 'PHASE 01',
    title: 'Zero-Friction Social Splitter',
    tagline: 'Instant, offline group bill splitting without setup hurdles',
    description: 'Core frictionless expense splitting, time-of-day predictive chips, 200+ keyword auto-tagging, and 24h soft-delete protection.',
    targetAudience: 'Casual outings, dinners, weekend getaways, roommates',
    flagKeys: ['enablePredictiveChips', 'enableRecycleBin', 'enableExplainThisNumber', 'enableStickyDayHeaders', 'enableCategoryColorRings', 'enableCompactLedgerView', 'enableCategoryReorder', 'enableWhatsNewHub', 'enableTabBackHistory', 'enableDeepLinkedTabs', 'enableExtendedUndo', 'enableTripStackSort'],
  },
  {
    id: 'phase2',
    phaseNumber: 2,
    code: 'PHASE 02',
    title: 'Active Group Collab & Natural Entry',
    tagline: 'Frictionless on-trip logging & shared trip organization',
    description: 'Hands-free voice quick-add with Hinglish NLP parsing, compressed receipt photos, collaborative packing & rich notes, and 4D duplicate expense warning.',
    targetAudience: 'Friends & families actively traveling together',
    flagKeys: ['enableVoiceInput', 'enableReceiptUpload', 'enableNotesAndChecklist', 'enableDuplicateDetector', 'enableTripChat', 'enableExpensePhotoLinking', 'enableExpenseDisputes', 'enableDigestNotifications', 'enableMemberLastSeen', 'enableQuietHours', 'enableExpenseApprovalThreshold', 'enablePersistentExpenseDraft'],
  },
  {
    id: 'phase3',
    phaseNumber: 3,
    code: 'PHASE 03',
    title: 'Smart Travel Navigator & Pass Hub',
    tagline: 'Boarding passes, live flight radar, and airport turnstile tools',
    description: 'Universal Travel Pass Wallet, Dynamic Island Next-Up capsule, optical barcode gate scanner, live flight/PNR status radar, smart packing assistant, and route stops.',
    targetAudience: 'Air & rail travelers, road-trippers, multi-city itineraries',
    flagKeys: [
      'enableTravelPasses',
      'enableNextUpCapsule',
      'enableGateScanner',
      'enableFlightRadar',
      'enablePackingAssistant',
      'enableRouteStops',
      'enableGeotagging',
      'enableIcsExport',
      'enableOfflineMapTiles',
      'enableLiveLocationShare',
      'enableMapCollapsedByDefault',
      'enableWeatherItineraryNudges',
      'enableDataSaverMode',
    ],
  },
  {
    id: 'phase4',
    phaseNumber: 4,
    code: 'PHASE 04',
    title: 'FinTech Pro & Global Jetsetter Suite',
    tagline: 'Advanced splits, multi-currency conversions & bank-grade security',
    description: 'Unequal exact/percent/weight splits, itemized restaurant receipt breakdowns, on-device OCR camera scanning, 160+ currency FX rates, and biometric screen lock.',
    targetAudience: 'Power users, digital nomads, international travelers',
    flagKeys: [
      'enableAdvancedSplits',
      'enableItemizedSplit',
      'enableReceiptOcr',
      'enableCurrencyFx',
      'enableMultiTripAnalytics',
      'enableBiometricAuth',
      'enableDocumentVault',
      'enableBurnRateInsight',
      'enableDateRangeMembership',
      'enableAutoCurrencyDetection',
      'enableSplitExclusionDefaults',
      'enableMultiPayerExpenses',
      'enableAmoledTheme',
    ],
  },
  {
    id: 'phase5',
    phaseNumber: 5,
    code: 'PHASE 05',
    title: 'Switch, Speed & Trust',
    tagline: 'Splitwise import, WhatsApp settle cards, faster logging, dated settlements',
    description: 'Convert groups from Splitwise, share a settlement card on WhatsApp, clone the last expense, remember default splits, and record settlements with a date and note.',
    targetAudience: 'Groups switching from Splitwise, repeat trip spenders, anyone settling over chat',
    flagKeys: [
      'enableSplitwiseImport',
      'enableWhatsAppSettlementShare',
      'enableCloneLastExpense',
      'enableRememberDefaultSplit',
      'enableSettlementDateNote',
      'enableSettlementHistory',
      'enableTripCloseout',
      'enableCrossTripSearch',
      'enableSettlementConfirmation',
      'enableTripShareLink',
      'enableContactInvite',
      'enableExpenseQuickFilterChips',
      'enableSyncQueueInspector',
    ],
  },
  {
    id: 'phase6',
    phaseNumber: 6,
    code: 'PHASE 06',
    title: 'WhatsApp Social & Chat Hub',
    tagline: 'Real-time social engagement, emoji reactions, outbox & Tab-1 elevation',
    description: 'Elevates Chat to primary Tab-1, removes chat from Notes, adds WhatsApp emoji reactions, swipe-to-reply, pinned notices, and offline outbox with status ticks.',
    targetAudience: 'Active group travelers, friends and families coordinating on the go',
    flagKeys: [
      'enableChatFirstNav',
      'enableChatReactionsAndReplies',
      'enableChatOfflineOutbox',
      'enableInChatEventCards',
      'enableChatAttachments',
      'enableChatVoiceNotes',
      'enableChatTypingIndicators',
      'enableChatReadReceipts',
      'enableTripbotNlExpenses',
      'enableChatUnreadOnNotes',
    ],
  },
  {
    id: 'phase7',
    phaseNumber: 7,
    code: 'PHASE 07',
    title: 'Commercial FinTech & Smart Splitting',
    tagline: 'Splitwise-grade debt simplification controls and direct debts',
    description: 'Allows trips to toggle between greedy flow debt minimization and direct bilateral reimbursement.',
    targetAudience: 'Power expense splitters, friend groups who prefer direct settling',
    flagKeys: [
      'enableSimplifyDebtsToggle',
    ],
  },
  {
    id: 'deferred',
    phaseNumber: 0,
    code: 'EXTRAS',
    title: 'Platform Extras & Back-Office Ops',
    tagline: 'Delighters, backup utilities, and administrative engineering tools',
    description: 'Trip Wrapped highlights, Squad Achievements, offline JSON snapshot backup, place search, feature suggestions, and admin tools.',
    targetAudience: 'All users and ops administrators',
    flagKeys: [
      'enableTripWrapped',
      'enableAchievements',
      'enableOfflineSnapshot',
      'enableAdvancedLocationSearch',
      'enableFeatureSuggestions',
      'enableKeywordTagging',
      'enableDemoSeeding',
      'enableUpiPayments',
    ],
  },
];

export const FEATURE_FLAGS_META: Record<FeatureFlagKey, FeatureFlagMeta> = {
  // Phase 1: Core Social Splitter
  enablePredictiveChips: {
    key: 'enablePredictiveChips',
    label: 'Predictive Quick-Expense Chips',
    description: 'Shows time-of-day suggestions (breakfast, cab, dinner) for 1-tap logging.',
    category: 'core',
    phase: 'phase1',
    defaultEnabledForUsers: true,
  },
  enableRecycleBin: {
    key: 'enableRecycleBin',
    label: 'Recycle Bin & 24h Soft-Delete',
    description: 'Safeguards deleted expenses in a 24-hour staging area with instant restore.',
    category: 'core',
    phase: 'phase1',
    defaultEnabledForUsers: true,
  },
  enableExplainThisNumber: {
    key: 'enableExplainThisNumber',
    label: 'Why This Amount? Settlement Audit',
    description: 'ⓘ on a suggested transfer explains the number, including the bill titles in that balance.',
    category: 'core',
    phase: 'phase1',
    defaultEnabledForUsers: false,
  },
  enableStickyDayHeaders: {
    key: 'enableStickyDayHeaders',
    label: 'Sticky Ledger Day Headers',
    description: 'Pins day headers with date and subtotal while scrolling the expense ledger feed.',
    category: 'core',
    phase: 'phase1',
    defaultEnabledForUsers: false,
  },
  enableCategoryColorRings: {
    key: 'enableCategoryColorRings',
    label: 'Category Icon Color Rings & Tabular Alignment',
    description: 'Ambient duo-tone color halo rings on expense category icons with tabular-number alignment.',
    category: 'core',
    phase: 'phase1',
    defaultEnabledForUsers: false,
  },
  enableCompactLedgerView: {
    key: 'enableCompactLedgerView',
    label: 'Compact Ledger View',
    description: 'Tighter row padding and smaller avatars/icons in the expense ledger for viewing more rows per screen.',
    category: 'core',
    phase: 'phase1',
    defaultEnabledForUsers: false,
  },
  enableCategoryReorder: {
    key: 'enableCategoryReorder',
    label: 'Manual Category Reorder',
    description: 'Reorder expense categories with up/down controls in Settings; order syncs across devices for the trip.',
    category: 'core',
    phase: 'phase1',
    defaultEnabledForUsers: false,
  },
  enableWhatsNewHub: {
    key: 'enableWhatsNewHub',
    label: "What's New on Version Screen",
    description: "Makes the version in Settings → About tappable, opening an iOS-style 'What's New' screen with this release's changes.",
    category: 'core',
    phase: 'phase1',
    defaultEnabledForUsers: false,
  },

  // Phase 2: Active Group Collab
  enableVoiceInput: {
    key: 'enableVoiceInput',
    label: 'Hands-Free Voice Quick-Add',
    description: 'Web Speech API listener with Hinglish number parser and acoustic feedback.',
    category: 'collab',
    phase: 'phase2',
    defaultEnabledForUsers: true,
  },
  enableReceiptUpload: {
    key: 'enableReceiptUpload',
    label: 'Receipt Photo Attachments',
    description: 'Allows capturing and attaching compressed receipt images to expenses.',
    category: 'collab',
    phase: 'phase2',
    defaultEnabledForUsers: true,
  },
  enableExpensePhotoLinking: {
    key: 'enableExpensePhotoLinking',
    label: 'Extra Expense Photos',
    description: 'Attach more photos to an already-saved expense, beyond the single primary receipt.',
    category: 'collab',
    phase: 'phase2',
    defaultEnabledForUsers: false,
  },
  enableExpenseDisputes: {
    key: 'enableExpenseDisputes',
    label: 'Dispute Flag on Expenses',
    description: 'Any participant can flag an expense as disputed; the flagger or a trip admin can resolve it.',
    category: 'collab',
    phase: 'phase2',
    defaultEnabledForUsers: false,
  },
  enableDigestNotifications: {
    key: 'enableDigestNotifications',
    label: 'Digest-Mode Notifications',
    description: 'One daily push summary instead of a push per event. Requires the digest_cron_secret Vault setup in migration 0087.',
    category: 'collab',
    phase: 'phase2',
    defaultEnabledForUsers: false,
  },
  enableQuietHours: {
    key: 'enableQuietHours',
    label: 'Quiet Hours',
    description: 'Per-user time window (e.g. 11pm-7am, in their local timezone) during which push notifications are suppressed.',
    category: 'collab',
    phase: 'phase2',
    defaultEnabledForUsers: false,
  },
  enableMemberLastSeen: {
    key: 'enableMemberLastSeen',
    label: 'Member Last Seen',
    description: 'Show Online now / last seen on member rows from live trip presence (remembered on this device).',
    category: 'collab',
    phase: 'phase2',
    defaultEnabledForUsers: false,
  },
  enableNotesAndChecklist: {
    key: 'enableNotesAndChecklist',
    label: 'Collaborative Notes & Checklist Hub',
    description: 'Enables the 5th tab for shared packing lists, Wi-Fi codes, and trip notes.',
    category: 'collab',
    phase: 'phase2',
    defaultEnabledForUsers: true,
  },
  enableDuplicateDetector: {
    key: 'enableDuplicateDetector',
    label: '4D Duplicate Expense Warning Guard',
    description: 'Heuristic check preventing duplicate check-ins or companion double-entries.',
    category: 'collab',
    phase: 'phase2',
    defaultEnabledForUsers: true,
  },
  enableTripChat: {
    key: 'enableTripChat',
    label: 'Trip Group Chat',
    description:
      'WhatsApp-style realtime chat for the trip. Lives under Notes by default; enable Primary Tab-1 Chat Navigation to elevate it to the bottom bar.',
    category: 'collab',
    phase: 'phase2',
    defaultEnabledForUsers: true,
  },
  enableExpenseApprovalThreshold: {
    key: 'enableExpenseApprovalThreshold',
    label: 'Big-Expense Mutual Approval',
    description:
      'Expenses above a per-trip threshold enter Pending Approval and are excluded from balances/analytics until a second member approves.',
    category: 'collab',
    phase: 'phase2',
    defaultEnabledForUsers: false,
  },

  // Phase 3: Smart Travel Navigator & Pass Hub
  enableTravelPasses: {
    key: 'enableTravelPasses',
    label: 'Universal Travel Pass Wallet',
    description: 'Central wallet for airline boarding passes, train tickets, and hotel vouchers.',
    category: 'transit',
    phase: 'phase3',
    defaultEnabledForUsers: true,
  },
  enableNextUpCapsule: {
    key: 'enableNextUpCapsule',
    label: '"Next Up" Travel Island Capsule',
    description: 'Pinned transit countdown capsule tracking imminent flights and trains within 36h.',
    category: 'transit',
    phase: 'phase3',
    defaultEnabledForUsers: true,
  },
  enableGateScanner: {
    key: 'enableGateScanner',
    label: 'High-Contrast Optical Gate Scanner',
    description: 'Inverted retina barcode viewer with Screen Wake Lock API for turnstiles.',
    category: 'transit',
    phase: 'phase3',
    defaultEnabledForUsers: true,
  },
  enableFlightRadar: {
    key: 'enableFlightRadar',
    label: 'Live Flight & Railways PNR Radar',
    description: 'Deep links to Flightradar24, FlightAware, ConfirmTkt, and RailYatri.',
    category: 'transit',
    phase: 'phase3',
    defaultEnabledForUsers: true,
  },
  enablePackingAssistant: {
    key: 'enablePackingAssistant',
    label: 'Smart Weather & Packing Assistant',
    description: 'Open-Meteo destination weather analysis & airline luggage rule checklist.',
    category: 'transit',
    phase: 'phase3',
    defaultEnabledForUsers: true,
  },
  enableRouteStops: {
    key: 'enableRouteStops',
    label: 'Interactive Route Stops Itinerary',
    description: 'Multi-city itinerary manager with arrival/departure dates and map pins.',
    category: 'transit',
    phase: 'phase3',
    defaultEnabledForUsers: true,
  },
  enableGeotagging: {
    key: 'enableGeotagging',
    label: 'GPS Geotagging & Journey Map',
    description: 'Auto GPS coordinates and MapLibre GL interactive spending trail.',
    category: 'geotagging',
    phase: 'phase3',
    defaultEnabledForUsers: true,
  },
  enableIcsExport: {
    key: 'enableIcsExport',
    label: 'ICS Calendar Export for Passes',
    description: 'Share flight/train/hotel passes to the device Calendar app (Web Share), or download a .ics file as fallback.',
    category: 'transit',
    phase: 'phase3',
    defaultEnabledForUsers: false,
  },
  enableOfflineMapTiles: {
    key: 'enableOfflineMapTiles',
    label: 'Offline Map Tile Caching',
    description: 'Caches MapLibre journey-map tiles so the last-viewed trip map still renders with no signal.',
    category: 'geotagging',
    phase: 'phase3',
    defaultEnabledForUsers: false,
  },
  enableLiveLocationShare: {
    key: 'enableLiveLocationShare',
    label: 'Live Location Share',
    description: 'Share a public, no-login link showing a member’s current position for a bounded 12h window.',
    category: 'geotagging',
    phase: 'phase3',
    defaultEnabledForUsers: false,
  },
  enableMapCollapsedByDefault: {
    key: 'enableMapCollapsedByDefault',
    label: 'Collapse Map by Default',
    description: 'Open a trip with the content sheet covering the map. Swipe down to peek the route.',
    category: 'geotagging',
    phase: 'phase3',
    defaultEnabledForUsers: false,
  },
  enableWeatherItineraryNudges: {
    key: 'enableWeatherItineraryNudges',
    label: 'Weather-Triggered Itinerary Nudges',
    description: 'Daily server check of each upcoming route-stop destination; pushes a nudge when bad weather is forecast for the next day.',
    category: 'transit',
    phase: 'phase3',
    defaultEnabledForUsers: false,
  },
  enableDataSaverMode: {
    key: 'enableDataSaverMode',
    label: 'Data Saver Mode',
    description: 'Keeps the trip map collapsed until manually opened and skips celebration animations, to cut mobile data and battery use while traveling.',
    category: 'transit',
    phase: 'phase3',
    defaultEnabledForUsers: false,
  },

  // Phase 4: FinTech Pro & Global Jetsetter Suite
  enableAdvancedSplits: {
    key: 'enableAdvancedSplits',
    label: 'Advanced Split Modes',
    description: 'Unlocks Exact amounts, Percentage, and Custom Weight split modes.',
    category: 'splits',
    phase: 'phase4',
    defaultEnabledForUsers: true,
  },
  enableItemizedSplit: {
    key: 'enableItemizedSplit',
    label: 'Itemized Receipt Splitting',
    description: 'Line-item dish assignment with automated tax and tip proration.',
    category: 'splits',
    phase: 'phase4',
    defaultEnabledForUsers: true,
  },
  enableReceiptOcr: {
    key: 'enableReceiptOcr',
    label: 'On-Device Tesseract Receipt OCR',
    description: 'Camera bill scanning and text/total extraction directly on device.',
    category: 'fintech',
    phase: 'phase4',
    defaultEnabledForUsers: true,
  },
  enableCurrencyFx: {
    key: 'enableCurrencyFx',
    label: 'Live Multi-Currency FX Converter',
    description: 'Real-time conversion across 160+ fiat currencies with offline lock.',
    category: 'fintech',
    phase: 'phase4',
    defaultEnabledForUsers: true,
  },
  enableMultiTripAnalytics: {
    key: 'enableMultiTripAnalytics',
    label: 'Master Multi-Trip Analytics',
    description: 'Cross-trip net balance, category breakdown, and spending charts.',
    category: 'fintech',
    phase: 'phase4',
    defaultEnabledForUsers: true,
  },
  enableBiometricAuth: {
    key: 'enableBiometricAuth',
    label: 'Biometric Screen Lock (WebAuthn)',
    description: 'Touch ID, Face ID, or Windows Hello passkey protection for trips.',
    category: 'security',
    phase: 'phase4',
    defaultEnabledForUsers: true,
  },
  enableDocumentVault: {
    key: 'enableDocumentVault',
    label: 'Document / ID Vault',
    description: 'Local-only, biometric-gated storage for passport, visa, and insurance scans. Never leaves the device.',
    category: 'security',
    phase: 'phase4',
    defaultEnabledForUsers: false,
  },
  enableBurnRateInsight: {
    key: 'enableBurnRateInsight',
    label: 'Spend Burn-Rate Forecast',
    description: 'Analytics card projecting total trip spend from the daily average so far, for trips currently in progress.',
    category: 'fintech',
    phase: 'phase4',
    defaultEnabledForUsers: false,
  },
  enableDateRangeMembership: {
    key: 'enableDateRangeMembership',
    label: 'Date-Range Member Participation',
    description: 'Members can have a join/leave date within the trip; new expenses default their split to only members present on that date.',
    category: 'splits',
    phase: 'phase4',
    defaultEnabledForUsers: false,
  },
  enableAutoCurrencyDetection: {
    key: 'enableAutoCurrencyDetection',
    label: 'Auto Currency Detection',
    description: 'Suggests the local currency on the expense form from device GPS location (reuses existing Geotag consent).',
    category: 'fintech',
    phase: 'phase4',
    defaultEnabledForUsers: false,
  },
  enableSplitExclusionDefaults: {
    key: 'enableSplitExclusionDefaults',
    label: 'Per-Category Split Exclusion Defaults',
    description: 'Set members who are excluded by default from a category\'s split (e.g. non-drinkers from Alcohol), applied automatically on new expenses.',
    category: 'splits',
    phase: 'phase4',
    defaultEnabledForUsers: false,
  },
  enableMultiPayerExpenses: {
    key: 'enableMultiPayerExpenses',
    label: 'Multi-Payer Shared Expenses',
    description: 'Allows single expenses to be fronted by multiple members in custom amounts with exact settlement math.',
    category: 'splits',
    phase: 'phase4',
    defaultEnabledForUsers: false,
  },
  enableAmoledTheme: {
    key: 'enableAmoledTheme',
    label: 'AMOLED Pure Black & High-Contrast Theme',
    description: 'Gates the battery-saving OLED Pure Black theme with high-contrast borders for bright daylight and night flights.',
    category: 'fintech',
    phase: 'phase4',
    defaultEnabledForUsers: false,
  },

  // Phase 5: Switch, Speed & Trust (safed by default)
  enableSplitwiseImport: {
    key: 'enableSplitwiseImport',
    label: 'Splitwise CSV Import',
    description: 'Import a Splitwise group spreadsheet into the active trip with member mapping.',
    category: 'splits',
    phase: 'phase5',
    defaultEnabledForUsers: false,
  },
  enableWhatsAppSettlementShare: {
    key: 'enableWhatsAppSettlementShare',
    label: 'WhatsApp Settlement Share Card',
    description: 'Share a settlement PNG card via WhatsApp or the system share sheet.',
    category: 'splits',
    phase: 'phase5',
    defaultEnabledForUsers: false,
  },
  enableCloneLastExpense: {
    key: 'enableCloneLastExpense',
    label: 'Clone Last Expense',
    description: 'Prefill the add-expense form from the most recent trip expense (date resets to today).',
    category: 'core',
    phase: 'phase5',
    defaultEnabledForUsers: false,
  },
  enableTabBackHistory: {
    key: 'enableTabBackHistory',
    label: 'Tab Back History',
    description: 'Back gesture / button walks through the tabs you visited (up to 5) instead of jumping straight to Expenses.',
    category: 'core',
    phase: 'phase1',
    defaultEnabledForUsers: false,
  },
  enableDeepLinkedTabs: {
    key: 'enableDeepLinkedTabs',
    label: 'Deep-Linked Tabs',
    description: 'Keep the open trip and tab in the URL so a refresh or shared link lands on the same screen.',
    category: 'core',
    phase: 'phase1',
    defaultEnabledForUsers: false,
  },
  enableExtendedUndo: {
    key: 'enableExtendedUndo',
    label: 'Extended Undo',
    description: 'Undo toast for member delete, member archive and recorded settlements.',
    category: 'core',
    phase: 'phase1',
    defaultEnabledForUsers: false,
  },
  enableTripStackSort: {
    key: 'enableTripStackSort',
    label: 'Trip Stack Sort Toggle',
    description: 'Adds a Sort: A–Z / Date toggle under the home trip stack. Swiping always steps alphabetically or by date order (left = next, right = previous).',
    category: 'core',
    phase: 'phase1',
    defaultEnabledForUsers: false,
  },
  enablePersistentExpenseDraft: {
    key: 'enablePersistentExpenseDraft',
    label: 'Persistent Expense Draft',
    description: 'Keep an unsaved new-expense draft for 24h, even after the app is closed, including payers, currency, location and itemized receipt.',
    category: 'collab',
    phase: 'phase2',
    defaultEnabledForUsers: false,
  },
  enableSyncQueueInspector: {
    key: 'enableSyncQueueInspector',
    label: 'Sync Queue Inspector',
    description: 'Offline queue shows readable items with errors, per-item Retry and Discard, and keeps failed changes instead of dropping them.',
    category: 'core',
    phase: 'phase5',
    defaultEnabledForUsers: false,
  },
  enableRememberDefaultSplit: {
    key: 'enableRememberDefaultSplit',
    label: 'Remember Default Split',
    description: 'Reuse the last split mode and participants on new expenses in this trip.',
    category: 'splits',
    phase: 'phase5',
    defaultEnabledForUsers: false,
  },
  enableTripCloseout: {
    key: 'enableTripCloseout',
    label: 'End-of-Trip Closeout',
    description: 'Guided review → settle remaining → lock the trip, plus a reminder when trip dates have ended.',
    category: 'splits',
    phase: 'phase5',
    defaultEnabledForUsers: false,
  },
  enableCrossTripSearch: {
    key: 'enableCrossTripSearch',
    label: 'Search Across All Trips',
    description: 'Cmd+K / home search finds expenses in every trip you belong to and opens the matching trip.',
    category: 'core',
    phase: 'phase5',
    defaultEnabledForUsers: false,
  },
  enableSettlementHistory: {
    key: 'enableSettlementHistory',
    label: 'Payment History / Installment Tracker',
    description: 'Groups partial settlements between the same two members into a running paid-so-far history instead of separate ledger rows.',
    category: 'splits',
    phase: 'phase5',
    defaultEnabledForUsers: false,
  },
  enableSettlementDateNote: {
    key: 'enableSettlementDateNote',
    label: 'Settlement Date & Note',
    description: 'Record a settlement with a chosen date and optional note on the ledger entry.',
    category: 'splits',
    phase: 'phase5',
    defaultEnabledForUsers: false,
  },
  enableSettlementConfirmation: {
    key: 'enableSettlementConfirmation',
    label: 'Two-Sided Settlement Confirmation',
    description: 'The recipient of a settlement must confirm receipt before it\'s marked fully settled, instead of trusting the payer\'s entry alone.',
    category: 'splits',
    phase: 'phase5',
    defaultEnabledForUsers: false,
  },
  enableTripShareLink: {
    key: 'enableTripShareLink',
    label: 'Read-Only Trip Share Link',
    description: 'Generate a revocable, no-login link showing a bounded read-only trip summary for people outside the trip.',
    category: 'core',
    phase: 'phase5',
    defaultEnabledForUsers: false,
  },
  enableContactInvite: {
    key: 'enableContactInvite',
    label: 'Invite From Phone Contacts',
    description: 'Pick a trip invitee from the device contact list (native only) and hand off to the system share sheet with the join link.',
    category: 'core',
    phase: 'phase5',
    defaultEnabledForUsers: false,
  },
  enableExpenseQuickFilterChips: {
    key: 'enableExpenseQuickFilterChips',
    label: 'Expenses Tab Quick-Filter Chip Bar',
    description: 'Horizontally scrollable 1-tap filter chips directly on the Expenses tab for instant filtering without opening drawers.',
    category: 'core',
    phase: 'phase5',
    defaultEnabledForUsers: false,
  },

  // Phase 6: WhatsApp Social & Chat Hub
  enableChatFirstNav: {
    key: 'enableChatFirstNav',
    label: 'Primary Tab-1 Chat Navigation',
    description:
      'Moves Chat from the Notes hub to Tab 1 on the bottom bar. Does not create Chat by itself — requires Trip Group Chat (enableTripChat). When OFF, Chat stays under Notes.',
    category: 'collab',
    phase: 'phase6',
    defaultEnabledForUsers: false,
  },
  enableChatReactionsAndReplies: {
    key: 'enableChatReactionsAndReplies',
    label: 'Chat Emoji Reactions & Quoted Replies',
    description: 'WhatsApp-style emoji reactions (👍, ❤️, 😂, 😮, 🙏), swipe-to-reply quoting, and pinned admin notices.',
    category: 'collab',
    phase: 'phase6',
    defaultEnabledForUsers: false,
  },
  enableChatOfflineOutbox: {
    key: 'enableChatOfflineOutbox',
    label: 'Offline Chat Outbox with Status Ticks',
    description: 'Queue messages in IndexedDB when offline with WhatsApp delivery indicators (🕒, ✓, ✓✓).',
    category: 'collab',
    phase: 'phase6',
    defaultEnabledForUsers: false,
  },
  enableInChatEventCards: {
    key: 'enableInChatEventCards',
    label: 'In-Chat Expense Event Cards',
    description: 'Auto-post compact expense cards into trip chat when someone adds a bill. Delete, restore, and settlement confirm update that same card in place (title, amount, tap to open).',
    category: 'collab',
    phase: 'phase6',
    defaultEnabledForUsers: false,
  },
  enableChatAttachments: {
    key: 'enableChatAttachments',
    label: 'Chat Attachment Tray',
    description: 'Composer + tray for camera, gallery, and attach-existing-expense cards (chat-media storage).',
    category: 'collab',
    phase: 'phase6',
    defaultEnabledForUsers: false,
  },
  enableChatVoiceNotes: {
    key: 'enableChatVoiceNotes',
    label: 'Chat Voice Notes',
    description: 'Hold-to-record voice bubbles in trip chat (separate from speech-to-text quick-add).',
    category: 'collab',
    phase: 'phase6',
    defaultEnabledForUsers: false,
  },
  enableChatTypingIndicators: {
    key: 'enableChatTypingIndicators',
    label: 'Chat Typing Indicators',
    description: 'Realtime “is typing…” presence on the trip chat channel.',
    category: 'collab',
    phase: 'phase6',
    defaultEnabledForUsers: false,
  },
  enableChatReadReceipts: {
    key: 'enableChatReadReceipts',
    label: 'Chat Read Receipts',
    description: 'Trip-level read cursors so senders see when peers have caught up (not per-message rows).',
    category: 'collab',
    phase: 'phase6',
    defaultEnabledForUsers: false,
  },
  enableTripbotNlExpenses: {
    key: 'enableTripbotNlExpenses',
    label: 'In-Chat @tripbot Expense Logging',
    description: 'Parse @tripbot natural-language lines into a confirm sheet, then create an expense.',
    category: 'collab',
    phase: 'phase6',
    defaultEnabledForUsers: false,
  },
  enableChatUnreadOnNotes: {
    key: 'enableChatUnreadOnNotes',
    label: 'Unread Badge on Notes Chat',
    description: 'Dot on Notes (and Chat tab when Chat-first is on) when there are new trip messages you have not opened. Does not add messages to the thread.',
    category: 'collab',
    phase: 'phase6',
    defaultEnabledForUsers: false,
  },

  // Phase 7: Commercial FinTech & Smart Splitting
  enableSimplifyDebtsToggle: {
    key: 'enableSimplifyDebtsToggle',
    label: '"Simplify Debts" Algorithm Toggle',
    description: 'Allow trip members to toggle between greedy debt flow minimization and direct bilateral reimbursement.',
    category: 'splits',
    phase: 'phase7',
    defaultEnabledForUsers: false,
  },

  // Extras & Unphased Platform Tools
  enableTripWrapped: {
    key: 'enableTripWrapped',
    label: 'Trip Wrapped Story Card & Highlights',
    description: 'Interactive year-end/trip-end highlights and spend personality cards.',
    category: 'core',
    phase: 'deferred',
    defaultEnabledForUsers: true,
  },
  enableAchievements: {
    key: 'enableAchievements',
    label: 'Trip Squad Achievements & Milestones',
    description: 'Gamified milestone badges (First Expense, Settle-Up Master, Global Roamer).',
    category: 'core',
    phase: 'deferred',
    defaultEnabledForUsers: true,
  },
  enableOfflineSnapshot: {
    key: 'enableOfflineSnapshot',
    label: 'Offline Snapshot JSON Data Backup',
    description: 'Complete offline JSON database export and backup migration tools.',
    category: 'admin',
    phase: 'deferred',
    defaultEnabledForUsers: true,
  },
  enableAdvancedLocationSearch: {
    key: 'enableAdvancedLocationSearch',
    label: 'Advanced Place Name Search & Map Picker',
    description: 'Nominatim geocoding place search and manual map pin picker.',
    category: 'geotagging',
    phase: 'deferred',
    defaultEnabledForUsers: true,
  },
  enableFeatureSuggestions: {
    key: 'enableFeatureSuggestions',
    label: 'Suggest a Feature Feedback Box',
    description: 'Allows travelers to submit feature feedback directly to the Ops Deck.',
    category: 'admin',
    phase: 'deferred',
    defaultEnabledForUsers: true,
  },
  enableKeywordTagging: {
    key: 'enableKeywordTagging',
    label: 'Custom Keyword & Brand Tag Editor',
    description: 'Exposes dictionary editor in Categories settings.',
    category: 'admin',
    phase: 'deferred',
    defaultEnabledForUsers: false,
  },
  enableDemoSeeding: {
    key: 'enableDemoSeeding',
    label: 'Demo Trip Data Seeding',
    description: 'Shows "Seed Demo Data" button in Settings.',
    category: 'admin',
    phase: 'deferred',
    defaultEnabledForUsers: false,
  },
  enableUpiPayments: {
    key: 'enableUpiPayments',
    label: '1-Tap UPI / Payment App Links (Deferred)',
    description: 'Out of scope for initial consumer rollout. Kept disabled.',
    category: 'splits',
    phase: 'deferred',
    defaultEnabledForUsers: false,
  },
};

export const DEFAULT_FEATURE_FLAGS: Record<FeatureFlagKey, boolean> = {
  // Phase 1 (Armed by default)
  enablePredictiveChips: true,
  enableRecycleBin: true,
  enableExplainThisNumber: false,
  enableStickyDayHeaders: false,
  enableCategoryColorRings: false,
  enableCompactLedgerView: false,
  enableCategoryReorder: false,
  enableWhatsNewHub: false,

  // Phase 2 (Armed by default)
  enableVoiceInput: true,
  enableReceiptUpload: true,
  enableNotesAndChecklist: true,
  enableDuplicateDetector: true,
  enableTripChat: true,
  enableExpensePhotoLinking: false,
  enableExpenseDisputes: false,
  enableDigestNotifications: false,
  enableMemberLastSeen: false,
  enableQuietHours: false,
  enableExpenseApprovalThreshold: false,

  // Phase 3 (Armed by default)
  enableTravelPasses: true,
  enableNextUpCapsule: true,
  enableGateScanner: true,
  enableFlightRadar: true,
  enablePackingAssistant: true,
  enableRouteStops: true,
  enableGeotagging: true,
  enableIcsExport: false,
  enableOfflineMapTiles: false,
  enableLiveLocationShare: false,
  enableMapCollapsedByDefault: false,
  enableWeatherItineraryNudges: false,
  enableDataSaverMode: false,

  // Phase 4 (Armed by default)
  enableAdvancedSplits: true,
  enableItemizedSplit: true,
  enableReceiptOcr: true,
  enableCurrencyFx: true,
  enableMultiTripAnalytics: true,
  enableBiometricAuth: true,
  enableDocumentVault: false,
  enableBurnRateInsight: false,
  enableDateRangeMembership: false,
  enableAutoCurrencyDetection: false,
  enableSplitExclusionDefaults: false,
  enableMultiPayerExpenses: false,
  enableAmoledTheme: false,

  // Phase 5 (safed by default)
  enableSplitwiseImport: false,
  enableWhatsAppSettlementShare: false,
  enableCloneLastExpense: false,
  enableRememberDefaultSplit: false,
  enableTabBackHistory: false,
  enableDeepLinkedTabs: false,
  enableExtendedUndo: false,
  enableTripStackSort: false,
  enablePersistentExpenseDraft: false,
  enableSyncQueueInspector: false,
  enableSettlementDateNote: false,
  enableSettlementHistory: false,
  enableTripCloseout: false,
  enableCrossTripSearch: false,
  enableSettlementConfirmation: false,
  enableTripShareLink: false,
  enableContactInvite: false,
  enableExpenseQuickFilterChips: false,

  // Phase 6 (WhatsApp Social & Chat Hub - safed by default)
  enableChatFirstNav: false,
  enableChatReactionsAndReplies: false,
  enableChatOfflineOutbox: false,
  enableInChatEventCards: false,
  enableChatAttachments: false,
  enableChatVoiceNotes: false,
  enableChatTypingIndicators: false,
  enableChatReadReceipts: false,
  enableTripbotNlExpenses: false,
  enableChatUnreadOnNotes: false,

  // Phase 7 (Commercial FinTech - safed by default)
  enableSimplifyDebtsToggle: false,

  // Platform Extras & Deferred
  enableTripWrapped: true,
  enableAchievements: true,
  enableOfflineSnapshot: true,
  enableAdvancedLocationSearch: true,
  enableFeatureSuggestions: true,
  enableKeywordTagging: false,
  enableDemoSeeding: false,
  enableUpiPayments: false,
};

export function getPhaseFlagKeys(phaseId: ReleasePhaseId): FeatureFlagKey[] {
  const phase = RELEASE_PHASES.find((p) => p.id === phaseId);
  return phase ? phase.flagKeys : [];
}

export function getPhaseStatus(
  phaseId: ReleasePhaseId,
  flags: Record<FeatureFlagKey, boolean>
): { activeCount: number; totalCount: number; status: 'armed' | 'partial' | 'safed' } {
  const keys = getPhaseFlagKeys(phaseId);
  if (keys.length === 0) return { activeCount: 0, totalCount: 0, status: 'safed' };
  let active = 0;
  for (const k of keys) {
    const isEnabled = flags[k] ?? FEATURE_FLAGS_META[k]?.defaultEnabledForUsers ?? false;
    if (isEnabled) active++;
  }
  return {
    activeCount: active,
    totalCount: keys.length,
    status: active === keys.length ? 'armed' : active > 0 ? 'partial' : 'safed',
  };
}

export function isFeatureActive(
  key: FeatureFlagKey,
  flags: Record<FeatureFlagKey, boolean>,
  context?: {
    isSuperadmin?: boolean;
    isTravelerPreview?: boolean;
    tripId?: string;
    userId?: string;
    tripOverrides?: Record<string, Record<string, boolean>>;
    userOverrides?: Record<string, Record<string, boolean>>;
  }
): boolean {
  // 1. User-specific override takes top precedence
  if (context?.userId && context.userOverrides?.[context.userId]?.[key] !== undefined) {
    return context.userOverrides[context.userId][key];
  }

  // 2. Trip-specific override takes second precedence
  if (context?.tripId && context.tripOverrides?.[context.tripId]?.[key] !== undefined) {
    return context.tripOverrides[context.tripId][key];
  }

  // 3. Global feature flag configured in switchboard (armed = true, safed = false)
  // Explicitly configured state ALWAYS governs so Arm/Safe actions immediately take effect
  if (flags && flags[key] !== undefined) {
    return flags[key];
  }

  // 4. Default fallback
  return FEATURE_FLAGS_META[key]?.defaultEnabledForUsers ?? false;
}
