import type { FeatureFlagKey, FeatureFlagMeta, ConsumerPackDef, ConsumerPackId } from '../types/admin';

export const CONSUMER_PACKS: ConsumerPackDef[] = [
  {
    id: 'core',
    packNumber: 1,
    code: 'CORE',
    title: 'Core — first and last minutes',
    tagline: 'Add, invite, settle, share, lock, same squad next trip',
    description: 'The money loop every traveler needs. Equal split, fast add, invite, settle over WhatsApp/UPI, view-only share, closeout, and new trip with this group. Arm this pack or the first 60 seconds and last 5 minutes stay weak.',
    targetAudience: 'Everyone. Cafe bills, weekends, any group that will log a bill.',
    flagKeys: [
      'enablePredictiveChips',
      'enableRecycleBin',
      'enableDuplicateDetector',
      'enableTripWrapped',
      'enableExplainThisNumber',
      'enableCloneLastExpense',
      'enableRememberDefaultSplit',
      'enablePersistentExpenseDraft',
      'enableHomeNetBalance',
      'enableCloneTripSquad',
      'enableTripCloseout',
      'enableWhatsAppSettlementShare',
      'enableUpiPayments',
      'enableTripShareLink',
      'enableExtendedUndo',
      'enableContactInvite',
      'enableNotesTalkPackPass',
      'enableProgressiveNextUp',
    ],
  },
  {
    id: 'trip',
    packNumber: 2,
    code: 'TRIP',
    title: 'Trip — on the road',
    tagline: 'Voice, receipts, Notes + quiet chat, packing, FX, map collapsed',
    description: 'Mid-trip logging without putting radar on the expenses tab. Chat stays under Notes. Advanced split modes are available when they change split, not as extra tabs.',
    targetAudience: 'Friends and families actively traveling together.',
    flagKeys: [
      'enableVoiceInput',
      'enableReceiptUpload',
      'enableNotesAndChecklist',
      'enableTripChat',
      'enablePackingAssistant',
      'enableGeotagging',
      'enableAdvancedLocationSearch',
      'enableCurrencyFx',
      'enableAdvancedSplits',
      'enableDeepLinkedTabs',
      'enableMapCollapsedByDefault',
    ],
  },
  {
    id: 'travel',
    packNumber: 3,
    code: 'TRAVEL',
    title: 'Travel — pass holders',
    tagline: 'Passes, Next-Up, scanner, flight/PNR radar — chrome hidden until a pass exists',
    description: 'Air and rail tools. Core Hide Next-Up Until a Pass Exists keeps the expenses tab clean on cafe-bill trips. Route stops stay off by default so this is not an itinerary product.',
    targetAudience: 'Air and rail travelers who add a boarding pass or ticket.',
    flagKeys: [
      'enableTravelPasses',
      'enableNextUpCapsule',
      'enableGateScanner',
      'enableFlightRadar',
      'enableIcsExport',
      'enableRouteStops',
      'enableOfflineMapTiles',
      'enableDataSaverMode',
    ],
  },
  {
    id: 'pro',
    packNumber: 4,
    code: 'PRO',
    title: 'Pro — power money',
    tagline: 'Itemized dishes, OCR, analytics, vault, multi-payer, Splitwise import',
    description: 'Power-splitter surfaces. Default off so first-open stays light. Optional later paid tier — never put Core settle/share in Pro.',
    targetAudience: 'Itemized dinners, digital nomads, groups switching from Splitwise.',
    flagKeys: [
      'enableItemizedSplit',
      'enableReceiptOcr',
      'enableMultiTripAnalytics',
      'enableBiometricAuth',
      'enableDocumentVault',
      'enableBurnRateInsight',
      'enableDateRangeMembership',
      'enableAutoCurrencyDetection',
      'enableSplitExclusionDefaults',
      'enableMultiPayerExpenses',
      'enableSimplifyDebtsToggle',
      'enableSettlementHistory',
      'enableSettlementDateNote',
      'enableSettlementConfirmation',
      'enableSplitwiseImport',
      'enableCrossTripSearch',
      'enableExpenseQuickFilterChips',
      'enableCompactLedgerView',
      'enableStickyDayHeaders',
      'enableCategoryColorRings',
      'enableCategoryReorder',
      'enableAmoledTheme',
      'enableKeywordTagging',
      'enableExpensePhotoLinking',
      'enableExpenseDisputes',
      'enableExpenseApprovalThreshold',
      'enableTripStackSort',
      'enableTabBackHistory',
    ],
  },
  {
    id: 'labs',
    packNumber: 5,
    code: 'LABS',
    title: 'Labs — do not ship',
    tagline: 'Chat-first, Tripbot, live location, achievements — keep built, keep off',
    description: 'Heavy or second-product experiments. Arming Labs by default is how the app gets heavy. Superadmin may test on a trip override.',
    targetAudience: 'Internal betas only. Not a traveler default.',
    flagKeys: [
      'enableChatFirstNav',
      'enableChatReactionsAndReplies',
      'enableChatOfflineOutbox',
      'enableInChatEventCards',
      'enableChatAttachments',
      'enableChatVoiceNotes',
      'enableChatTypingIndicators',
      'enableChatReadReceipts',
      'enableTripbotNlExpenses',
      'enableChatUnreadOnNotes',
      'enableLiveLocationShare',
      'enableWeatherItineraryNudges',
      'enableAchievements',
      'enableWhatsNewHub',
      'enableDigestNotifications',
      'enableQuietHours',
      'enableMemberLastSeen',
      'enableCloseoutPulse',
    ],
  },
  {
    id: 'ops',
    packNumber: 6,
    code: 'OPS',
    title: 'Ops — Superadmin only',
    tagline: 'Demo seed, JSON snapshot, feedback inbox, sync inspector',
    description: 'Back-office tools. Default off for travelers. Superadmin can arm per session.',
    targetAudience: 'Ops Deck administrators.',
    flagKeys: [
      'enableOfflineSnapshot',
      'enableFeatureSuggestions',
      'enableDemoSeeding',
      'enableSyncQueueInspector',
    ],
  },
];

export const FEATURE_FLAGS_META: Record<FeatureFlagKey, FeatureFlagMeta> = {
  // Phase 1: Core Social Splitter
  enablePredictiveChips: {
    key: 'enablePredictiveChips',
    label: 'Predictive Quick-Expense Chips',
    description: 'Shows time-of-day suggestions (breakfast, cab, dinner) for 1-tap logging.',
    category: 'core',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableRecycleBin: {
    key: 'enableRecycleBin',
    label: 'Recycle Bin & 24h Soft-Delete',
    description: 'Safeguards deleted expenses in a 24-hour staging area with instant restore.',
    category: 'core',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableExplainThisNumber: {
    key: 'enableExplainThisNumber',
    label: 'Why This Amount? Settlement Audit',
    description: 'ⓘ Why? on a suggested settlement transfer explains the amount, including the bill titles in that balance.',
    category: 'core',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableStickyDayHeaders: {
    key: 'enableStickyDayHeaders',
    label: 'Sticky Ledger Day Headers',
    description: 'Pins day headers with date and subtotal while scrolling the expense ledger feed.',
    category: 'core',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableCategoryColorRings: {
    key: 'enableCategoryColorRings',
    label: 'Category Icon Color Rings & Tabular Alignment',
    description: 'Ambient duo-tone color halo rings on expense category icons with tabular-number alignment.',
    category: 'core',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableCompactLedgerView: {
    key: 'enableCompactLedgerView',
    label: 'Compact Ledger View',
    description: 'Tighter row padding and smaller avatars/icons in the expense ledger for viewing more rows per screen.',
    category: 'core',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableCategoryReorder: {
    key: 'enableCategoryReorder',
    label: 'Manual Category Reorder',
    description: 'Reorder expense categories with up/down controls in Settings; order syncs across devices for the trip.',
    category: 'core',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableWhatsNewHub: {
    key: 'enableWhatsNewHub',
    label: "What's New on Version Screen",
    description: "Makes the version in Settings → About tappable, opening an iOS-style 'What's New' screen with this release's changes.",
    category: 'core',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },

  // Phase 2: Active Group Collab
  enableVoiceInput: {
    key: 'enableVoiceInput',
    label: 'Hands-Free Voice Quick-Add',
    description: 'Web Speech API listener with Hinglish number parser and acoustic feedback.',
    category: 'collab',
    pack: 'trip',
    defaultEnabledForUsers: true,
  },
  enableReceiptUpload: {
    key: 'enableReceiptUpload',
    label: 'Receipt Photo Attachments',
    description: 'Allows capturing and attaching compressed receipt images to expenses.',
    category: 'collab',
    pack: 'trip',
    defaultEnabledForUsers: true,
  },
  enableExpensePhotoLinking: {
    key: 'enableExpensePhotoLinking',
    label: 'Extra Expense Photos',
    description: 'Attach more photos to an already-saved expense, beyond the single primary receipt.',
    category: 'collab',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableExpenseDisputes: {
    key: 'enableExpenseDisputes',
    label: 'Dispute Flag on Expenses',
    description: 'Any participant can flag an expense as disputed; the flagger or a trip admin can resolve it.',
    category: 'collab',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableDigestNotifications: {
    key: 'enableDigestNotifications',
    label: 'Digest-Mode Notifications',
    description: 'One daily push summary instead of a push per event. Requires the digest_cron_secret Vault setup in migration 0087.',
    category: 'collab',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
  enableQuietHours: {
    key: 'enableQuietHours',
    label: 'Quiet Hours',
    description: 'Per-user time window (e.g. 11pm-7am, in their local timezone) during which push notifications are suppressed.',
    category: 'collab',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
  enableMemberLastSeen: {
    key: 'enableMemberLastSeen',
    label: 'Member Last Seen',
    description: 'Show Online now / last seen on member rows from live trip presence (remembered on this device).',
    category: 'collab',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
  enableNotesAndChecklist: {
    key: 'enableNotesAndChecklist',
    label: 'Collaborative Notes & Checklist Hub',
    description: 'Enables the 5th tab for shared packing lists, Wi-Fi codes, and trip notes.',
    category: 'collab',
    pack: 'trip',
    defaultEnabledForUsers: true,
  },
  enableNotesTalkPackPass: {
    key: 'enableNotesTalkPackPass',
    label: 'Notes Hub Talk / Pack / Pass Labels',
    description: 'Relabels Notes segments to Talk / Pack / Pass / Notes (Chat, Checklist, Passes when OFF). Requires Notes hub.',
    category: 'collab',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableDuplicateDetector: {
    key: 'enableDuplicateDetector',
    label: '4D Duplicate Expense Warning Guard',
    description: 'Heuristic check preventing duplicate check-ins or companion double-entries.',
    category: 'collab',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableTripChat: {
    key: 'enableTripChat',
    label: 'Trip Group Chat',
    description:
      'WhatsApp-style realtime chat for the trip. Lives under Notes by default; enable Primary Tab-1 Chat Navigation to elevate it to the bottom bar.',
    category: 'collab',
    pack: 'trip',
    defaultEnabledForUsers: true,
  },
  enableExpenseApprovalThreshold: {
    key: 'enableExpenseApprovalThreshold',
    label: 'Big-Expense Mutual Approval',
    description:
      'Expenses above a per-trip threshold enter Pending Approval and are excluded from balances/analytics until a second member approves.',
    category: 'collab',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },

  // Phase 3: Smart Travel Navigator & Pass Hub
  enableTravelPasses: {
    key: 'enableTravelPasses',
    label: 'Universal Travel Pass Wallet',
    description: 'Central wallet for airline boarding passes, train tickets, and hotel vouchers.',
    category: 'transit',
    pack: 'travel',
    defaultEnabledForUsers: true,
  },
  enableNextUpCapsule: {
    key: 'enableNextUpCapsule',
    label: '"Next Up" Travel Island Capsule',
    description: 'Pinned transit countdown capsule tracking imminent flights and trains within 36h.',
    category: 'transit',
    pack: 'travel',
    defaultEnabledForUsers: true,
  },
  enableProgressiveNextUp: {
    key: 'enableProgressiveNextUp',
    label: 'Hide Next-Up Until a Pass Exists',
    description: 'Expenses-tab Next-Up capsule stays hidden until the trip has at least one boarding pass or ticket. Radar and scanner stay on pass cards.',
    category: 'transit',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableGateScanner: {
    key: 'enableGateScanner',
    label: 'High-Contrast Optical Gate Scanner',
    description: 'Inverted retina barcode viewer with Screen Wake Lock API for turnstiles.',
    category: 'transit',
    pack: 'travel',
    defaultEnabledForUsers: true,
  },
  enableFlightRadar: {
    key: 'enableFlightRadar',
    label: 'Live Flight & Railways PNR Radar',
    description: 'Deep links to Flightradar24, FlightAware, ConfirmTkt, and RailYatri.',
    category: 'transit',
    pack: 'travel',
    defaultEnabledForUsers: true,
  },
  enablePackingAssistant: {
    key: 'enablePackingAssistant',
    label: 'Smart Weather & Packing Assistant',
    description: 'Open-Meteo destination weather analysis & airline luggage rule checklist.',
    category: 'transit',
    pack: 'trip',
    defaultEnabledForUsers: true,
  },
  enableRouteStops: {
    key: 'enableRouteStops',
    label: 'Interactive Route Stops Itinerary',
    description: 'Multi-city itinerary manager with arrival/departure dates and map pins.',
    category: 'transit',
    pack: 'travel',
    defaultEnabledForUsers: false,
  },
  enableGeotagging: {
    key: 'enableGeotagging',
    label: 'GPS Geotagging & Journey Map',
    description: 'Auto GPS coordinates and MapLibre GL interactive spending trail.',
    category: 'geotagging',
    pack: 'trip',
    defaultEnabledForUsers: true,
  },
  enableIcsExport: {
    key: 'enableIcsExport',
    label: 'ICS Calendar Export for Passes',
    description: 'Share flight/train/hotel passes to the device Calendar app (Web Share), or download a .ics file as fallback.',
    category: 'transit',
    pack: 'travel',
    defaultEnabledForUsers: true,
  },
  enableOfflineMapTiles: {
    key: 'enableOfflineMapTiles',
    label: 'Offline Map Tile Caching',
    description: 'Caches MapLibre journey-map tiles so the last-viewed trip map still renders with no signal.',
    category: 'geotagging',
    pack: 'travel',
    defaultEnabledForUsers: false,
  },
  enableLiveLocationShare: {
    key: 'enableLiveLocationShare',
    label: 'Live Location Share',
    description: 'Share a public, no-login link showing a member’s current position for a bounded 12h window.',
    category: 'geotagging',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
  enableMapCollapsedByDefault: {
    key: 'enableMapCollapsedByDefault',
    label: 'Collapse Map by Default',
    description: 'Open a trip with the content sheet covering the map. Swipe down to peek the route.',
    category: 'geotagging',
    pack: 'trip',
    defaultEnabledForUsers: true,
  },
  enableWeatherItineraryNudges: {
    key: 'enableWeatherItineraryNudges',
    label: 'Weather-Triggered Itinerary Nudges',
    description: 'Daily server check of each upcoming route-stop destination; pushes a nudge when bad weather is forecast for the next day.',
    category: 'transit',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
  enableDataSaverMode: {
    key: 'enableDataSaverMode',
    label: 'Data Saver Mode',
    description: 'Keeps the trip map collapsed until manually opened and skips celebration animations, to cut mobile data and battery use while traveling.',
    category: 'transit',
    pack: 'travel',
    defaultEnabledForUsers: false,
  },

  // Phase 4: FinTech Pro & Global Jetsetter Suite
  enableAdvancedSplits: {
    key: 'enableAdvancedSplits',
    label: 'Advanced Split Modes',
    description: 'Unlocks Exact amounts, Percentage, and Custom Weight split modes.',
    category: 'splits',
    pack: 'trip',
    defaultEnabledForUsers: true,
  },
  enableItemizedSplit: {
    key: 'enableItemizedSplit',
    label: 'Itemized Receipt Splitting',
    description: 'Line-item dish assignment with automated tax and tip proration.',
    category: 'splits',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableReceiptOcr: {
    key: 'enableReceiptOcr',
    label: 'On-Device Tesseract Receipt OCR',
    description: 'Camera bill scanning and text/total extraction directly on device.',
    category: 'fintech',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableCurrencyFx: {
    key: 'enableCurrencyFx',
    label: 'Live Multi-Currency FX Converter',
    description: 'Real-time conversion across 160+ fiat currencies with offline lock.',
    category: 'fintech',
    pack: 'trip',
    defaultEnabledForUsers: true,
  },
  enableMultiTripAnalytics: {
    key: 'enableMultiTripAnalytics',
    label: 'Master Multi-Trip Analytics',
    description: 'Cross-trip net balance, category breakdown, and spending charts.',
    category: 'fintech',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableBiometricAuth: {
    key: 'enableBiometricAuth',
    label: 'Biometric Screen Lock (WebAuthn)',
    description: 'Touch ID, Face ID, or Windows Hello passkey protection for trips.',
    category: 'security',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableDocumentVault: {
    key: 'enableDocumentVault',
    label: 'Document / ID Vault',
    description: 'Local-only, biometric-gated storage for passport, visa, and insurance scans. Never leaves the device.',
    category: 'security',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableBurnRateInsight: {
    key: 'enableBurnRateInsight',
    label: 'Spend Burn-Rate Forecast',
    description: 'Analytics card projecting total trip spend from the daily average so far, for trips currently in progress.',
    category: 'fintech',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableDateRangeMembership: {
    key: 'enableDateRangeMembership',
    label: 'Date-Range Member Participation',
    description: 'Members can have a join/leave date within the trip; new expenses default their split to only members present on that date.',
    category: 'splits',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableAutoCurrencyDetection: {
    key: 'enableAutoCurrencyDetection',
    label: 'Auto Currency Detection',
    description: 'Suggests the local currency on the expense form from device GPS location (reuses existing Geotag consent).',
    category: 'fintech',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableSplitExclusionDefaults: {
    key: 'enableSplitExclusionDefaults',
    label: 'Per-Category Split Exclusion Defaults',
    description: 'Set members who are excluded by default from a category\'s split (e.g. non-drinkers from Alcohol), applied automatically on new expenses.',
    category: 'splits',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableMultiPayerExpenses: {
    key: 'enableMultiPayerExpenses',
    label: 'Multi-Payer Shared Expenses',
    description: 'Allows single expenses to be fronted by multiple members in custom amounts with exact settlement math.',
    category: 'splits',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableAmoledTheme: {
    key: 'enableAmoledTheme',
    label: 'AMOLED Pure Black & High-Contrast Theme',
    description: 'Gates the battery-saving OLED Pure Black theme with high-contrast borders for bright daylight and night flights.',
    category: 'fintech',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },

  // Phase 5: Switch, Speed & Trust (safed by default)
  enableSplitwiseImport: {
    key: 'enableSplitwiseImport',
    label: 'Splitwise CSV Import',
    description: 'Import a Splitwise group spreadsheet into the active trip with member mapping.',
    category: 'splits',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableWhatsAppSettlementShare: {
    key: 'enableWhatsAppSettlementShare',
    label: 'WhatsApp Settlement Share Card',
    description: 'Share a settlement PNG card via WhatsApp or the system share sheet.',
    category: 'splits',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableCloneLastExpense: {
    key: 'enableCloneLastExpense',
    label: 'Clone Last Expense',
    description: 'Prefill the add-expense form from the most recent trip expense (date resets to today).',
    category: 'core',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableTabBackHistory: {
    key: 'enableTabBackHistory',
    label: 'Tab Back History',
    description: 'Back gesture / button walks through the tabs you visited (up to 5) instead of jumping straight to Expenses.',
    category: 'core',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableDeepLinkedTabs: {
    key: 'enableDeepLinkedTabs',
    label: 'Deep-Linked Tabs',
    description: 'Keep the open trip and tab in the URL so a refresh or shared link lands on the same screen.',
    category: 'core',
    pack: 'trip',
    defaultEnabledForUsers: true,
  },
  enableExtendedUndo: {
    key: 'enableExtendedUndo',
    label: 'Extended Undo',
    description: 'Undo toast for member delete, member archive and recorded settlements.',
    category: 'core',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableTripStackSort: {
    key: 'enableTripStackSort',
    label: 'Trip Stack Sort Toggle',
    description: 'Adds a Sort: A–Z / Date toggle under the home trip stack. Swiping always steps alphabetically or by date order (left = next, right = previous).',
    category: 'core',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enablePersistentExpenseDraft: {
    key: 'enablePersistentExpenseDraft',
    label: 'Persistent Expense Draft',
    description: 'Keep an unsaved new-expense draft for 24h, even after the app is closed, including payers, currency, location and itemized receipt.',
    category: 'collab',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableSyncQueueInspector: {
    key: 'enableSyncQueueInspector',
    label: 'Sync Queue Inspector',
    description: 'Offline queue shows readable items with errors, per-item Retry and Discard, and keeps failed changes instead of dropping them.',
    category: 'core',
    pack: 'ops',
    defaultEnabledForUsers: false,
  },
  enableRememberDefaultSplit: {
    key: 'enableRememberDefaultSplit',
    label: 'Remember Default Split',
    description: 'Reuse the last split mode and participants on new expenses in this trip.',
    category: 'splits',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableTripCloseout: {
    key: 'enableTripCloseout',
    label: 'End-of-Trip Closeout',
    description: 'Guided review → settle remaining → lock the trip. After lock, opens Trip Wrapped when that flag is on.',
    category: 'splits',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableCrossTripSearch: {
    key: 'enableCrossTripSearch',
    label: 'Search Across All Trips',
    description: 'Cmd+K / home search finds expenses in every trip you belong to and opens the matching trip.',
    category: 'core',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableSettlementHistory: {
    key: 'enableSettlementHistory',
    label: 'Payment History / Installment Tracker',
    description: 'Groups partial settlements between the same two members into a running paid-so-far history instead of separate ledger rows.',
    category: 'splits',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableSettlementDateNote: {
    key: 'enableSettlementDateNote',
    label: 'Settlement Date & Note',
    description: 'Record a settlement with a chosen date and optional note on the ledger entry.',
    category: 'splits',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableSettlementConfirmation: {
    key: 'enableSettlementConfirmation',
    label: 'Two-Sided Settlement Confirmation',
    description: 'The recipient of a settlement must confirm receipt before it\'s marked fully settled, instead of trusting the payer\'s entry alone.',
    category: 'splits',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableTripShareLink: {
    key: 'enableTripShareLink',
    label: 'Read-Only Trip Share Link',
    description: 'Generate a revocable, no-login link showing a bounded read-only trip summary. Shown first in Invite & Share so people who will not install can still see totals.',
    category: 'core',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableHomeNetBalance: {
    key: 'enableHomeNetBalance',
    label: 'Home Cross-Trip You Owe / Are Owed',
    description: 'Shows a You are owed / You owe strip on the home trip stack, plus Add to log on the trip in dates (or last used).',
    category: 'splits',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableCloneTripSquad: {
    key: 'enableCloneTripSquad',
    label: 'New Trip With This Group',
    description: 'Duplicate copies name-only squad members onto the new trip, copies remembered split habits, and labels the action New trip with this group. Off = Duplicate Trip, creator only.',
    category: 'core',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableContactInvite: {
    key: 'enableContactInvite',
    label: 'Invite From Phone Contacts',
    description: 'Pick a trip invitee from the device contact list (native only) and hand off to the system share sheet with the join link.',
    category: 'core',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableExpenseQuickFilterChips: {
    key: 'enableExpenseQuickFilterChips',
    label: 'Expenses Tab Quick-Filter Chip Bar',
    description: 'Horizontally scrollable 1-tap filter chips directly on the Expenses tab for instant filtering without opening drawers.',
    category: 'core',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },

  // Phase 6: WhatsApp Social & Chat Hub
  enableChatFirstNav: {
    key: 'enableChatFirstNav',
    label: 'Primary Tab-1 Chat Navigation',
    description:
      'Moves Chat from the Notes hub to Tab 1 on the bottom bar. Does not create Chat by itself — requires Trip Group Chat (enableTripChat). When OFF, Chat stays under Notes.',
    category: 'collab',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
  enableChatReactionsAndReplies: {
    key: 'enableChatReactionsAndReplies',
    label: 'Chat Emoji Reactions & Quoted Replies',
    description: 'WhatsApp-style emoji reactions (👍, ❤️, 😂, 😮, 🙏), swipe-to-reply quoting, and pinned admin notices.',
    category: 'collab',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
  enableChatOfflineOutbox: {
    key: 'enableChatOfflineOutbox',
    label: 'Offline Chat Outbox with Status Ticks',
    description: 'Queue messages in IndexedDB when offline with WhatsApp delivery indicators (🕒, ✓, ✓✓).',
    category: 'collab',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
  enableInChatEventCards: {
    key: 'enableInChatEventCards',
    label: 'In-Chat Expense Event Cards',
    description: 'Auto-post compact expense cards into trip chat when someone adds a bill. Delete, restore, and settlement confirm update that same card in place (title, amount, tap to open).',
    category: 'collab',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
  enableChatAttachments: {
    key: 'enableChatAttachments',
    label: 'Chat Attachment Tray',
    description: 'Composer + tray for camera, gallery, and attach-existing-expense cards (chat-media storage).',
    category: 'collab',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
  enableChatVoiceNotes: {
    key: 'enableChatVoiceNotes',
    label: 'Chat Voice Notes',
    description: 'Hold-to-record voice bubbles in trip chat (separate from speech-to-text quick-add).',
    category: 'collab',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
  enableChatTypingIndicators: {
    key: 'enableChatTypingIndicators',
    label: 'Chat Typing Indicators',
    description: 'Realtime “is typing…” presence on the trip chat channel.',
    category: 'collab',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
  enableChatReadReceipts: {
    key: 'enableChatReadReceipts',
    label: 'Chat Read Receipts',
    description: 'Trip-level read cursors so senders see when peers have caught up (not per-message rows).',
    category: 'collab',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
  enableTripbotNlExpenses: {
    key: 'enableTripbotNlExpenses',
    label: 'In-Chat @tripbot Expense Logging',
    description: 'Parse @tripbot natural-language lines into a confirm sheet, then create an expense.',
    category: 'collab',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
  enableChatUnreadOnNotes: {
    key: 'enableChatUnreadOnNotes',
    label: 'Unread Badge on Notes Chat',
    description: 'Dot on Notes (and Chat tab when Chat-first is on) when there are new trip messages you have not opened. Does not add messages to the thread.',
    category: 'collab',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },

  // Phase 7: Commercial FinTech & Smart Splitting
  enableSimplifyDebtsToggle: {
    key: 'enableSimplifyDebtsToggle',
    label: '"Simplify Debts" Algorithm Toggle',
    description: 'Allow trip members to toggle between greedy debt flow minimization and direct bilateral reimbursement.',
    category: 'splits',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },

  // Extras & Unphased Platform Tools
  enableTripWrapped: {
    key: 'enableTripWrapped',
    label: 'Trip Wrapped Story Card & Highlights',
    description: 'Interactive year-end/trip-end highlights and spend personality cards.',
    category: 'core',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableAchievements: {
    key: 'enableAchievements',
    label: 'Trip Squad Achievements & Milestones',
    description: 'Gamified milestone badges (First Expense, Settle-Up Master, Global Roamer).',
    category: 'core',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
  enableOfflineSnapshot: {
    key: 'enableOfflineSnapshot',
    label: 'Offline Snapshot JSON Data Backup',
    description: 'Complete offline JSON database export and backup migration tools.',
    category: 'admin',
    pack: 'ops',
    defaultEnabledForUsers: false,
  },
  enableAdvancedLocationSearch: {
    key: 'enableAdvancedLocationSearch',
    label: 'Advanced Place Name Search & Map Picker',
    description: 'Nominatim geocoding place search and manual map pin picker.',
    category: 'geotagging',
    pack: 'trip',
    defaultEnabledForUsers: true,
  },
  enableFeatureSuggestions: {
    key: 'enableFeatureSuggestions',
    label: 'Suggest a Feature Feedback Box',
    description: 'Allows travelers to submit feature feedback directly to the Ops Deck.',
    category: 'admin',
    pack: 'ops',
    defaultEnabledForUsers: false,
  },
  enableKeywordTagging: {
    key: 'enableKeywordTagging',
    label: 'Custom Keyword & Brand Tag Editor',
    description: 'Exposes dictionary editor in Categories settings.',
    category: 'admin',
    pack: 'pro',
    defaultEnabledForUsers: false,
  },
  enableDemoSeeding: {
    key: 'enableDemoSeeding',
    label: 'Demo Trip Data Seeding',
    description: 'Shows "Seed Demo Data" button in Settings.',
    category: 'admin',
    pack: 'ops',
    defaultEnabledForUsers: false,
  },
  enableUpiPayments: {
    key: 'enableUpiPayments',
    label: '1-Tap UPI on settlement rows',
    description: 'UPI Pay chip on each settlement transfer (GPay, PhonePe, Paytm, or QR). Not a separate tab.',
    category: 'splits',
    pack: 'core',
    defaultEnabledForUsers: true,
  },
  enableCloseoutPulse: {
    key: 'enableCloseoutPulse',
    label: 'One-tap closeout pulse',
    description: 'After lock: “Would you use this for the next trip?” Yes / Not this group / Skip. Superadmin sees the % on Growth. Off: lock still two buttons, no survey. Not a form and not a new tab.',
    category: 'core',
    pack: 'labs',
    defaultEnabledForUsers: false,
  },
};

export const DEFAULT_FEATURE_FLAGS: Record<FeatureFlagKey, boolean> = {
  // Core — first and last minutes (default ON)
  enablePredictiveChips: true,
  enableRecycleBin: true,
  enableDuplicateDetector: true,
  enableTripWrapped: true,
  enableExplainThisNumber: true,
  enableCloneLastExpense: true,
  enableRememberDefaultSplit: true,
  enablePersistentExpenseDraft: true,
  enableHomeNetBalance: true,
  enableCloneTripSquad: true,
  enableTripCloseout: true,
  enableWhatsAppSettlementShare: true,
  enableUpiPayments: true,
  enableTripShareLink: true,
  enableExtendedUndo: true,
  enableContactInvite: true,
  enableNotesTalkPackPass: true,
  enableProgressiveNextUp: true,

  // Trip — on the road (default ON)
  enableVoiceInput: true,
  enableReceiptUpload: true,
  enableNotesAndChecklist: true,
  enableTripChat: true,
  enablePackingAssistant: true,
  enableGeotagging: true,
  enableAdvancedLocationSearch: true,
  enableCurrencyFx: true,
  enableAdvancedSplits: true,
  enableDeepLinkedTabs: true,
  enableMapCollapsedByDefault: true,

  // Travel — pass holders (chrome gated; route stops / tiles / data-saver OFF)
  enableTravelPasses: true,
  enableNextUpCapsule: true,
  enableGateScanner: true,
  enableFlightRadar: true,
  enableIcsExport: true,
  enableRouteStops: false,
  enableOfflineMapTiles: false,
  enableDataSaverMode: false,

  // Pro — power money (default OFF)
  enableItemizedSplit: false,
  enableReceiptOcr: false,
  enableMultiTripAnalytics: false,
  enableBiometricAuth: false,
  enableDocumentVault: false,
  enableBurnRateInsight: false,
  enableDateRangeMembership: false,
  enableAutoCurrencyDetection: false,
  enableSplitExclusionDefaults: false,
  enableMultiPayerExpenses: false,
  enableSimplifyDebtsToggle: false,
  enableSettlementHistory: false,
  enableSettlementDateNote: false,
  enableSettlementConfirmation: false,
  enableSplitwiseImport: false,
  enableCrossTripSearch: false,
  enableExpenseQuickFilterChips: false,
  enableCompactLedgerView: false,
  enableStickyDayHeaders: false,
  enableCategoryColorRings: false,
  enableCategoryReorder: false,
  enableAmoledTheme: false,
  enableKeywordTagging: false,
  enableExpensePhotoLinking: false,
  enableExpenseDisputes: false,
  enableExpenseApprovalThreshold: false,
  enableTripStackSort: false,
  enableTabBackHistory: false,

  // Labs — do not ship (default OFF)
  enableChatFirstNav: false,
  enableChatReactionsAndReplies: false,
  enableChatOfflineOutbox: false,
  enableInChatEventCards: false,
  enableChatAttachments: false,
  enableChatVoiceNotes: false,
  enableChatTypingIndicators: false,
  enableChatReadReceipts: false,
  enableTripbotNlExpenses: false,
  enableChatUnreadOnNotes: false,
  enableLiveLocationShare: false,
  enableWeatherItineraryNudges: false,
  enableAchievements: false,
  enableWhatsNewHub: false,
  enableDigestNotifications: false,
  enableQuietHours: false,
  enableMemberLastSeen: false,
  enableCloseoutPulse: false,

  // Ops — Superadmin only (default OFF)
  enableOfflineSnapshot: false,
  enableFeatureSuggestions: false,
  enableDemoSeeding: false,
  enableSyncQueueInspector: false,
};

export function getPackFlagKeys(packId: ConsumerPackId): FeatureFlagKey[] {
  const pack = CONSUMER_PACKS.find((p) => p.id === packId);
  return pack ? pack.flagKeys : [];
}

export function getPackStatus(
  packId: ConsumerPackId,
  flags: Record<FeatureFlagKey, boolean>
): { activeCount: number; totalCount: number; status: 'armed' | 'partial' | 'safed' } {
  const keys = getPackFlagKeys(packId);
  if (keys.length === 0) return { activeCount: 0, totalCount: 0, status: 'safed' };
  let active = 0;
  for (const k of keys) {
    const isEnabled = flags[k] ?? FEATURE_FLAGS_META[k]?.defaultEnabledForUsers ?? false;
    if (isEnabled) active++;
  }
  return {
    activeCount: active,
    totalCount: keys.length,
    status: active === keys.length ? 'armed' : active > 0 ? 'partial' : 'safed',
  };
}

export function isFeatureActive(
  key: FeatureFlagKey,
  flags: Record<FeatureFlagKey, boolean>,
  context?: {
    isSuperadmin?: boolean;
    isTravelerPreview?: boolean;
    tripId?: string;
    userId?: string;
    tripOverrides?: Record<string, Record<string, boolean>>;
    userOverrides?: Record<string, Record<string, boolean>>;
  }
): boolean {
  // 1. User-specific override takes top precedence
  if (context?.userId && context.userOverrides?.[context.userId]?.[key] !== undefined) {
    return context.userOverrides[context.userId][key];
  }

  // 2. Trip-specific override takes second precedence
  if (context?.tripId && context.tripOverrides?.[context.tripId]?.[key] !== undefined) {
    return context.tripOverrides[context.tripId][key];
  }

  // 3. Global feature flag configured in switchboard (armed = true, safed = false)
  // Explicitly configured state ALWAYS governs so Arm/Safe actions immediately take effect
  if (flags && flags[key] !== undefined) {
    return flags[key];
  }

  // 4. Default fallback
  return FEATURE_FLAGS_META[key]?.defaultEnabledForUsers ?? false;
}
